spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/workshop_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: workshop-api

logging:
  level:
    com.workshop: DEBUG

server:
  port: 8080